ARG NODE_VERSION=14
ARG NEXT_PUBLIC_SOURCE_COMMIT=None

FROM node:${NODE_VERSION} AS node
WORKDIR /code
COPY . .
RUN npm ci
ENV PATH $APP_SRC/node_modules/.bin:$PATH
ENV NEXT_PUBLIC_EXAMPLE $NEXT_PUBLIC_EXAMPLE
ENV EXAMPLE $EXAMPLE
RUN npm run build