ARG NODE_VERSION=14
ARG NEXT_PUBLIC_SOURCE_COMMIT=None

FROM node:${NODE_VERSION} AS node
WORKDIR /code
COPY . .
RUN npm ci
ENV PATH $APP_SRC/node_modules/.bin:$PATH
ENV NEXT_PUBLIC_BUILD $NEXT_PUBLIC_BUILD
ENV BUILD $BUILD
RUN npm run build